### ISSUE TITLE
runtime_error on start

### ISSUE THREAD

**Issue by 76house** [liskin/hybrid-screenclone#1]
Hi,

as described in http://zachstechnotes.blogspot.de/2012/04/post-title.html, I have installed bumblebee, patched my intel driver with xserver-xorg-video-intel-2.18.0_virtual_crtc, set virtual screen with xrandr, built screenclone from sources and got the following message when trying to start screenclone:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  screenclone.cc:78 display
Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])`

I use Ubuntu 12.04 64bit with Gnome-Shell 3.4.1 on Lenovo W520 with Nvidia Optimus (Intel 3000 HD + Nvidia quatro 1000).

BR,
Martin

**Comment by liskin** [comment]
Apparently screenclone can't connect to one of your X servers. Try something like:

```
xauth remove :1
xauth list :0 | awk '{ print "xauth add :1", $2, $3 }' | sh
```

**Comment by 76house** [comment]
Thanks, that helped :)
