### ISSUE TITLE
obsoleted

### ISSUE THREAD

**Issue by AsaAyers** [liskin/hybrid-screenclone#12]
> This program has been obsoleted by xserver-xorg-video-intel 2.99.

With hybrid-screenclone obsoleted, do you think you could point me in the direction of any guides you're aware of for getting this to work under xserver-xorg-video-intel?

I found your project through http://sagark.org/optimal-ubuntu-graphics-setup-for-thinkpads/. I have a Lenovo W530 running 14.10, but those directions are for 12.04 and don't all apply any more.

**Comment by liskin** [comment]
I'm sorry, but I've never looked for these guides as I had to get these things working before there could have been any. But basically all you have to do is install bumblebee, run intel-virtual-output -b and then you should be able to use xrandr or even a graphical monitor manager just as if everything was connected to the intel.

**Comment by AsaAyers** [comment]
No problem. Thanks.
