### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by rayxu123** [liskin/hybrid-screenclone#9]
Hi liskin,

I keep on getting run time errors when calling screenclone.

I have followed http://sagark.org/optimal-ubuntu-graphics-setup-for-thinkpads/ guide (using the correct xserver-xorg-video-intel patch version).  I am running Ubuntu 12.10 on a Lenovo W520 (Intel i7, Nvidia Quadro 1000M).  I installed bumblebee and patched the driver successfully.  

When I execute screenclone, regardless of parameters or superuser, I get:

terminate called after throwing an instance of 'std::runtime_error'
what(): screenclone.cc:97 display
Aborted (core dumped)

Could you please provide a solution to this please?  I am trying to setup dual monitors that I need to do things on very soon.

Thanks!

**Comment by liskin** [comment]
That error means it can't connect to one of the displays, likely because of xauth. Perhaps you haven't followed the howto properly.

**Comment by tskaifeLC** [comment]
I also got this error but restarting seemed to fix the issue.
